-- =====================================================
-- DARKKNIGHT STUDIO — Storage Buckets & Policies
-- Run in Supabase SQL Editor after schema + RLS
-- =====================================================

-- Public media (project images, banners, team avatars, news images)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'public-media',
  'public-media',
  true,
  5242880, -- 5MB
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/svg+xml']
)
ON CONFLICT (id) DO NOTHING;

-- Private ticket attachments
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'ticket-attachments',
  'ticket-attachments',
  false,
  10485760, -- 10MB
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'application/pdf', 'text/plain', 'application/zip']
)
ON CONFLICT (id) DO NOTHING;

-- Project downloadable files
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'project-files',
  'project-files',
  true,
  52428800, -- 50MB
  NULL -- allow common types
)
ON CONFLICT (id) DO NOTHING;

-- ========== STORAGE POLICIES ==========

-- public-media: anyone can read
CREATE POLICY "Public read public-media"
ON storage.objects FOR SELECT
USING (bucket_id = 'public-media');

-- only admins can upload/update/delete public-media
CREATE POLICY "Admin upload public-media"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'public-media'
  AND EXISTS (
    SELECT 1 FROM admins WHERE user_id = auth.uid() AND is_active = true
  )
);

CREATE POLICY "Admin update public-media"
ON storage.objects FOR UPDATE
USING (
  bucket_id = 'public-media'
  AND EXISTS (
    SELECT 1 FROM admins WHERE user_id = auth.uid() AND is_active = true
  )
);

CREATE POLICY "Admin delete public-media"
ON storage.objects FOR DELETE
USING (
  bucket_id = 'public-media'
  AND EXISTS (
    SELECT 1 FROM admins WHERE user_id = auth.uid() AND is_active = true
  )
);

-- ticket-attachments: private
-- Insert: allow authenticated or even anon for ticket flow (app controls)
CREATE POLICY "Insert ticket attachments"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'ticket-attachments');

-- Read: only admins (visitors use signed URLs generated by admin or limited policy)
CREATE POLICY "Admin read ticket attachments"
ON storage.objects FOR SELECT
USING (
  bucket_id = 'ticket-attachments'
  AND EXISTS (
    SELECT 1 FROM admins WHERE user_id = auth.uid() AND is_active = true
  )
);

CREATE POLICY "Admin delete ticket attachments"
ON storage.objects FOR DELETE
USING (
  bucket_id = 'ticket-attachments'
  AND EXISTS (
    SELECT 1 FROM admins WHERE user_id = auth.uid() AND is_active = true
  )
);

-- project-files
CREATE POLICY "Public read project-files"
ON storage.objects FOR SELECT
USING (bucket_id = 'project-files');

CREATE POLICY "Admin manage project-files"
ON storage.objects FOR ALL
USING (
  bucket_id = 'project-files'
  AND EXISTS (
    SELECT 1 FROM admins WHERE user_id = auth.uid() AND is_active = true
  )
)
WITH CHECK (
  bucket_id = 'project-files'
  AND EXISTS (
    SELECT 1 FROM admins WHERE user_id = auth.uid() AND is_active = true
  )
);
